# -*- coding: utf-8 -*-
"""4operacoes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b0RF7zHRvvlG6xB1wispUnAXPRWUpWWT

Resultado de operações com base em imput do usuário
"""

num1=float(input('digite um número:'))

num2=float(input('digite outro número:'))

try:
  print(num1,'+',num2,'=',num1+num2,'\n',\
      num1,'-',num2,'=',num1-num2,'\n',\
      num1,'*',num2,'=',num1*num2,'\n',\
      num1,'/',num2,'=',num1/num2)
except ZeroDivisionError:
  print('não existe divisão por 0')