# -*- coding: utf-8 -*-
"""Ano de Nascimento

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jWRWutS7mQ_MY4bn8xV9zmf_P8bnP4iI
"""

Idade = int(input("Em que ano você nasceu? "))

if Idade > 2006 :
  print("Você é menor de idade.")
else :
  print("Você é maior de idade.")