# -*- coding: utf-8 -*-
"""Ano de Nascimento

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jWRWutS7mQ_MY4bn8xV9zmf_P8bnP4iI
"""

Idade = int(input("Em que ano você nasceu? "))

AnoAtual = int(input("Em que ano está? "))

anos = (AnoAtual - Idade)
print(anos)

if anos >= 18 :
  print("Você é maior de idade.")
else :
  print("Você é menor de idade.")