# -*- coding: utf-8 -*-
"""Aprovado ou não aprovado

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KZqtTAxGUhbeRsc_AVFkPDyZx0EeiyBP
"""

aluno1 = 7

aluno2 = 5

media = float(6)

if aluno1 >= media :
  print("Aprovado!")
if aluno1 < media :
  print("Não aprovado!")

if aluno2 >= media :
  print("Aprovado!")
if aluno2 < media :
  print("Não aprovado!")