# -*- coding: utf-8 -*-
"""Calculadora

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iOim3Yskkxcljd1Rgazf90Z2QrzHkybZ
"""

from random import randint

print(randint(0, 1000))

numero1 = randint(0, 1000)
numero2 = randint(0, 1000)
print(numero1)
print(numero2)

#apenas anotando os resultados
resultado_soma = (numero1 + numero2)
print("O resultado da soma é:", resultado_soma, "\n")
resultado_sub = (numero1 - numero2)
print("O resultado da subtração é:", resultado_sub, "\n")
resultado_div = (numero1 / numero2)
print("O resultado da divisão é:", resultado_div, "\n")
resultado_mul = (numero1 * numero2)
print("O resultado da multiplicação é:", resultado_mul, "\n")

print("Resolva as quatro operações: \n")
#soma--------------------------------------------
print("Quanto é", numero1,"+",numero2, "?")
resultado = int(input())
if resultado == (numero1 + numero2) :
  print("Certa resposta!\n")
else:
  print("Resposta errada!\n")
#------------------------------------------------

#subtração---------------------------------------
print("Quanto é", numero1, "-", numero2, "?")
resultado = int(input())
if resultado == (numero1 - numero2):
  print("Certa resposta!\n")
else:
  print("Resposta errada!\n")
#------------------------------------------------

#divisão-----------------------------------------
print("Quanto é", numero1, "÷", numero2, "?")
resultado = int(input())
if resultado == (numero1 / numero2):
  print("Certa resposta!\n")
else:
  print("Resposta errada!\n")
#------------------------------------------------

#multiplicação-----------------------------------
print("Quanto é", numero1, "*", numero2, "?")
resultado = int(input())
if resultado == (numero1 * numero2):
  print("Certa resposta!")
else:
  print("Resposta errada!")
#------------------------------------------------