# -*- coding: utf-8 -*-
"""calculadora

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QosRnw2El6S_tuKfcW1Hf0-Jjt6Nd1h6
"""

a=float(input("Informe o número A: "))

if a==0:
 print('Tu tá de brincadeira rapaz executa o código certo aí')
 exit()

"""1. adição
2. subtração
3. multiplicação
4. divisão
"""

c=float(input("digite o número da operação que você deseja fazer: "))

if c==1:
 b=float(input('Informe o número B que você deseja adicionar somar: '))
elif c==2:
 b=float(input('Informe o número B que você deseja subtrair: '))
elif c==3:
 b=float(input('Informe o número B que você deseja multiplicar: '))
elif c==4:
 b=float(input('Informe o número B que você deseja dividir: '))
else:
  print("Tu tá de brincadeira rapaz executa o código certo aí")
exit()

if c==1:
 print("O resultado de A+B é: ",a+b)
elif c==2:
  print("O resultado de A-B é: ",a-b)
elif c==3:
  print("O resultado de A*B é: ",a*b)
elif c==4:
  print("O resultado de A/B é: ",a/b)