# -*- coding: utf-8 -*-
"""Condicional Simples

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rbleL1iWykH6af1I6SZw6J2cKAcw5nGA
"""

media = float(input("Informe a media: "))

if media >= 6 :
  print("Aprovado!")

if media < 6 :
  print("Não aprovado!")