# -*- coding: utf-8 -*-
"""Constante PI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OEVb_UIK6SyimgF01Rww0SmEiDNA5qmR
"""

pi = 3.141516171819
raio = 5
h = 10

def volume_lata_oleo(volume) :
  volume = pi * (raio*2) * h
  return volume
print(f'O volume da lata de óleo é {pi:.4f}')