# -*- coding: utf-8 -*-
"""Define media maior e menor numero.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FZlRN9NHtgFKJK0tYDky6bUFjTgO-N95
"""

# Inicializa as variáveis para armazenar o maior, menor e soma dos valores
maior = float('-inf')
menor = float('inf')
soma = 0

# Loop para ler 10 valores inteiros
for i in range(1, 11):
    valor = int(input(f"Digite o {i}º valor inteiro: "))

    # Atualiza o maior valor, se necessário
    if valor > maior:
        maior = valor

    # Atualiza o menor valor, se necessário
    if valor < menor:
        menor = valor

    # Adiciona o valor à soma
    soma += valor

# Calcula a média dos valores
media = soma / 10
7
# Imprime os resultados
print(f"O maior valor é: {maior}")
print(f"O menor valor é: {menor}")
print(f"A média dos valores é: {media}")