# -*- coding: utf-8 -*-
"""deznumeros.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18tsVO0jUTK_uyLf-vSYC1dqm0J8leg8M

Programa que solicita uma lista de números e retorna o maior, o menor e a média dentre eles
"""

maior=float(input('Digite um num:')) #aqui
menor=maior
soma=float()

for item in range (9):
  num=float(input('Digite um número'))
  if menor > num:
    menor=num
  if maior < num:
    maior=num
  soma=soma+num


print('maior:',maior)
print('menor:',menor)
print('média:',soma/10)