# -*- coding: utf-8 -*-
"""fatorial

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15FUpUH17rihHYo6z-MYwNeRu7SRVneqe
"""

f=int(input("Digite um número: "))
ff=1
for j in range (1,f+1):
 ff=ff*j
print("O fatorial desse número é: ",ff)