# -*- coding: utf-8 -*-
"""febre

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Taubga-A8rp5C_i221EbI51REJUVfVQa
"""

media=float()
temp=float()
for t in range(1,6):
  te=float(input('Digite a temperatura do paciente {}: '.format(t)))
  temp=te
  if temp<37.3 and temp>35:
    print('O paciente {} está normal'.format(t))
  elif temp>37.2 and temp<39:
    print('O paciente {} está com febre'.format(t))
  elif temp>38.9:
    print('O paciente {} está com muita febre'.format(t))
  elif temp<35:
    print('O paciente está com hipotermia')
  elif temp>39.9:
    print('O paciente está com hipertermia')
  media=media+te
print("A média de temperatura dos pacintes é: ",media/5)