# -*- coding: utf-8 -*-
"""for pares

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VthXk4Z34gHHu2z5S_9eTPl2KfuYqD0A
"""

a=float()
for a in range(0,101,2):
 print(a)