# -*- coding: utf-8 -*-
"""futebol

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FnwWVw2oK8rTJZbVwntaW4E6c8gXNBM-
"""

sfc=float(input("Quantos gols o Santos marcou? "))

sccp=float(input("Quantos gols o corinthians marcou? "))

if sfc>sccp:
  print("Santos ganhou")
elif sfc==sccp:
  print("empate")
else:
  print("Corinthians ganhou")
