# -*- coding: utf-8 -*-
"""hipotenusa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vXhBu-aMJgxDlpnwAkxWeJ-cuckGHuGA

Cálculo de valor da hipotenusa
"""

co=float(input('digite o valor do primeiro cateto:'))

ca=float(input('digite o valor do segundo cateto:'))

h=(ca**2+co**2)**(1/2)

print('o valor da sua hipotenusa é:',h)

