# -*- coding: utf-8 -*-
"""Hipotenusa

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZYrx8_V82Tik_l8z8ivrP3Ajz6DUMXzb
"""

a = 4
b = 3
hipotenusa = (a*a) + (b*b)
print(hipotenusa*hipotenusa)