# -*- coding: utf-8 -*-
"""idade média ps

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uu_Naaqi6c3H1tlgUERPV-FDa87xyjaY
"""

m=float()
h=float()
media=float()
p=float()
nmr=float()
t=float()
te=float()
n=int(input("Digite quantas pessoas são: "))

while nmr<n:
  nmr=nmr+1
  s=float(input('Digite o número do seu sexo: 1:masculino 2:feminino '))
  if s==1:
    i=float(input("digite sua idade: "))
    h=h+i
    te=te+1
  if s==2:
    id=float(input("digite sua idade: "))
    m=m+id
    t=t+1
print("a média da idade dos homens é: ",h/te)
print('a média da idade dos homens é: ',m/t)