# -*- coding: utf-8 -*-
"""Iguais ou diferentes

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_VLl32rzkWQ-BjC-e2fvTtCu5sqgGcVJ
"""

numero1 = int(input("Digite um numero: "))
numero2 = int(input("Digite outro numero: "))

if numero1 == numero2 :
  print("Os números são iguais entre si.")
else :
  print("Os números são diferentes entre si.")