# -*- coding: utf-8 -*-
"""Indentificador de categoria.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BaUDN4jODvHc-eNUtBcF-zmpfVelVmXZ
"""

idade=int(input("coloque sua idade:"))

if idade >= 5 and idade <= 7:
        categoria = "Infantil A"
elif idade >= 8 and idade <= 11:
        categoria = "Infantil B"
elif idade >= 12 and idade <= 13:
        categoria = "Juvenil A"
elif idade >= 14 and idade <= 17:
        categoria = "Juvenil B"
else:
        categoria = "Adulto"

print("Voce é da turma:",categoria)