# -*- coding: utf-8 -*-
"""inverter texto

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1psztKqFBJpeAz8kMEdw8Jx_NffDJSVS4
"""

txt=input("Digite algo: ")
txt=txt[::-1]
print(txt)