# -*- coding: utf-8 -*-
"""Maioridade.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/171G2_xPjlcdqTL6hwYqZBBryH0Po4BbT

Programa para dizer se o usuário é maior de idade
"""

from datetime import *

today=(date.today())

d,m,y=input('digite seu dia mês e ano de nascimento separado por espaços:').split()

d=int(d)
m=int(m)
y=int(y)

date=datetime(y,m,d)
print(date)

if today.year-date.year<=18 and today.day>=date.day and today.month>=date.month:
  print('Você não pode ser preso')
else:
  print('Você pode ser preso')