# -*- coding: utf-8 -*-
"""media.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12WS1IkqZumbTfRTD00zvIPafIBK2Fw-_
"""

nota1,nota2=input('digite duas notas de aluno:').split()

nota1=float(nota1)

nota2=float(nota2)

media=(nota1+nota2)/2

print()
if media >=6:
  print('Aprovado')
else:
  print('Não aprovado')