# -*- coding: utf-8 -*-
"""Menor e Maior

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c0WiGN6IMfVTPlCWfkbO9P013RXyaqsD
"""

valor1 = int(input("Digite o primeiro valor: "))
valor2 = int(input("Digite o segundo valor: "))

if valor1 < valor2 :
  print("O primeiro valor é menor que o segundo.")
if valor1 > valor2 :
  print("O primeiro valor é maior que o segundo.")

if valor2 > valor1 :
  print("O segundo valor é maior que o primeiro.")
if valor2 < valor1 :
  print("O segundo valor não é maior que o primeiro.")