# -*- coding: utf-8 -*-
"""Média Aritmética

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v70oy3z9Ct5hdP8lXQ5ZZjeW--wthK3z
"""

prova1 = 6
prova2 = 7
prova3 = 8
media = (prova1 + prova2 + prova3)/3
print(media)