# -*- coding: utf-8 -*-
"""múltiplo de 7 mas não de 5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k99reyBuvie57L_ZyrqY8VM4_ZVW1jed
"""

sete=[7,14,21,28,42,49,56,63,77,84,91,99]
print(sete)