# -*- coding: utf-8 -*-
"""Nadador

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17g2Qix6RTlQ8VNziNz483hQYk6XSiAaK
"""

def classificar_nadador(idade) :
  if idade >= 5 and idade <= 7 :
    return "Infantil A"
  elif idade >= 8 and idade <= 11 :
    return "Infantil B"
  elif idade == 12 and idade == 13 :
    return "Juvenil A"
  elif idade >= 14 and idade <= 17 :
    return "Juvenil B"
  else:
    return "Adultos"

nadador = int(input("Qual a idade do nadador? "))
classificacao = classificar_nadador(nadador)
print("A classificação do nadador é", classificacao)