# -*- coding: utf-8 -*-
"""Natação

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SRNF8Ff2NVSenuI-cDu1oZ44aVoywj0z
"""

i=float(input("Digite sua idade: "))

if i<5:
 print("Você não tem idade suficiente para participar")
elif i>4.9 and i<8:
 print("Você está na categoria infantil A")
elif i>7.9 and i<11:
 print("Você está na categoria infantil B")
elif i>11.9 and i<14:
 print("Você está na categoria juvenil A")
elif i>13.9 and i<18:
 print("Você está na categoria juvenil B")
else:
 print("Você está na categoria de adultos")