# -*- coding: utf-8 -*-
"""Notador de graus.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ei2WVvmEpA9oRboCku9zT2hPDJQ4LHiK
"""

def classificar_temperatura(temperatura):
    if temperatura < 37.2:
        return "normal"
    elif temperatura < 38:
        return "estado febril"
    elif temperatura < 39:
        return "com febre"
    else:
        return "com febre alta"

temperaturas = []

num_pessoas = int(input("Quantas pessoas deseja analisar? "))

for i in range(num_pessoas):
    temperatura = input(f"Digite a temperatura do cliente {i + 1} (em Celsius): ")
    if temperatura.isdigit() or (temperatura[1:].isdigit() and temperatura[0] == "-" and len(temperatura) > 1):
        temperatura = float(temperatura)
        if temperatura >= 0:
            temperaturas.append(temperatura)
            print(f"A temperatura do cliente {i + 1} está {classificar_temperatura(temperatura)}.")
        else:
            print("Por favor, digite uma temperatura válida.")
    else:
        print("Por favor, digite um número válido.")

if temperaturas:
    media_temperaturas = sum(temperaturas) / len(temperaturas)
    print(f"\nForam analisadas {len(temperaturas)} pessoas.")
    print(f"A média de temperatura entre as pessoas analisadas é de {media_temperaturas:.2f}°C.")
else:
    print("Nenhuma temperatura foi inserida.")