# -*- coding: utf-8 -*-
"""Par e Ímpar

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YtmONw_zZR17b3GRNHZAwsDn7nEwfPbI
"""

numero = int(input("Escolha um número qualquer: "))

if numero % 2 == 0 :
  print("O número é par.")
else :
  print("O número é ímpar")