# -*- coding: utf-8 -*-
"""pares.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BOWqCRmof0u4C86fXNJvRiSme2Og3XZm

Programa que cria uma lista de números pares e printa ao usuário
"""

list=[]
for num in range(0,101,2):
  list.append(num)
print('os pares são:',list)