# -*- coding: utf-8 -*-
"""parouimpar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jHN1K6s0FtK0Udngk5Ov3RZP2RkzjuL7

Programa para dizer se um número digitado é par ou ímpar
"""

n=float(input('digite um número:'))

if(n%2)==0:
  print('Esse número é par')
else:
  print('Esse número não é par')