# -*- coding: utf-8 -*-
"""qualomaior.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fkflh24Fb5F2HuuYHcGvqw-LuXZGRVpk

Programa para dizer qual o maior número entre dois numeros digitados pelo usuário.
"""

n,n2=(input('digite dois números: ')).split()

n=float(n)

n2=float(n2)

if n>n2:
  print('o primeiro número é maior que o primeiro')

if n<n2:
  print('o segundo número é maior que o primeiro')

print('números:',n,n2)