# -*- coding: utf-8 -*-
"""Quiz dos numeros.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TudtAwLmwmnp3pDWqX8WEfy9cE86yIJ_
"""

num1 = float(input("Digite o primeiro número decimal: "))
num2 = float(input("Digite o segundo número decimal (diferente de zero para divisão): "))

soma = float(input(f"Quanto é {num1} + {num2} :"))
subtracao = float(input(f"Quanto é {num1} -  {num2} :"))
multiplicacao = float(input(f"Quanto é {num1} x {num2} :"))
if num2 != 0:
    divisao = float(input(f"Qual é o resultado da divisão de {num1} / {num2} :"))

#resultados de todas as contas ------------------------------------------------------------
else:
    divisao = "Não é possivel dividir por zero"

if soma == num1 + num2:
    print("Resultado da soma está correto!")
else:
    print("Resultado da soma está incorreto.")

if subtracao == num1 - num2:
    print("Resultado da subtração está correto!")
else:
      print("Resultado da subtração está incorreto.")

if multiplicacao == num1 * num2:
    print("Resultado da multiplicação está correto!")
else:
    print("Resultado da multiplicação está incorreto.")

if num2 != 0:
    if divisao == num1 / num2:
        print("Resultado da divisão está correto!")
    else:
        print("Resultado da divisão está incorreto.")
else:
    print("Resultado da divisão:", divisao)