# -*- coding: utf-8 -*-
"""Reservatório(Água)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZvdJqzbQT2dM7G87SINDdz2GTzRWGRhv
"""

altura = float(input("Digite o valor da altura em centímetros: \n"))
largura = float(input("Digite o valor da largura em centímetros: \n"))
comprimento = float(input("Digite o valor do comprimento em centímetros: \n"))

consumo_medio_litros_dia = float(input("Digite o consumo médio diário dos utilizadores: "))
print(consumo_medio_litros_dia,"L")

capacidade_total_litros = (altura * largura * comprimento) / 1000
print(float(capacidade_total_litros))

autonomia_dias = capacidade_total_litros / consumo_medio_litros_dia

if autonomia_dias < 2:
   classificacao = "Consumo elevado"
elif 2 <= autonomia_dias <= 7:
   classificacao = "Consumo moderado"
else:
   classificacao = "Consumo reduzido"

print("\nCapacidade total do reservatório: {:.2f} litros".format(capacidade_total_litros))
print("Autonomia do reservatório: {:.2f} dias".format(autonomia_dias))
print("Classificação do consumo: ", classificacao)