# -*- coding: utf-8 -*-
"""Salario.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rKYaJyF7rVCKcemY24McN604DLjn2k8S

Cálculo de valor de aumento de salário
"""

sali=float(input('digite o valor do seu salário: '))

aum=float(input('digite o valor do seu aumento:'))

salf= sali+(aum/100)*sali

print('seu salário passará a ser: ', salf)