# -*- coding: utf-8 -*-
"""Salário

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DTqfQao5KgyLF15PQp0tDikhY6IKXD_7
"""

SalarioAtual = int(input("Qual sua renda atual? "))
percentual = (10/100)

SalarioAtualizado = SalarioAtual + (SalarioAtual * percentual)
print(int(SalarioAtualizado))