# -*- coding: utf-8 -*-
"""salário

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nArrhv2GB33Q7c2f2CrhVdLazVW-7E0E
"""

s=float(input("Valor do salário atual: "))

a=float(input('Valor do aumento em porcentagem: '))

n=(s+(s/100)*a)

print("Seu novo salário é: ",n)