# -*- coding: utf-8 -*-
"""Soma de idades .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WQm2NZ_wkRX2tl0mRbgENlEZqWzeF9bU
"""

# Inicializa as variáveis para armazenar a soma das idades de homens e mulheres, e o número de homens e mulheres
soma_idade_homem = 0
soma_idade_mulher = 0
contador_homem = 0
contador_mulher = 0

# Loop para ler as idades e sexos das pessoas
while True:
    idade_str = input("Digite a idade da pessoa (ou 'sair' para encerrar): ")

    # Verifica se o usuário deseja sair
    if idade_str.lower() == 'sair':
        break

    idade = int(idade_str)
    sexo = input("Digite o sexo da pessoa (M para masculino, F para feminino): ").upper()

    # Verifica o sexo e atualiza as variáveis apropriadas
    if sexo == 'M':
        soma_idade_homem += idade
        contador_homem += 1
    elif sexo == 'F':
        soma_idade_mulher += idade
        contador_mulher += 1
    else:
        print("Sexo inválido. Por favor, digite M para masculino ou F para feminino.")

# Calcula as médias
media_idade_homem = soma_idade_homem / max(1, contador_homem)  # Evita divisão por zero
media_idade_mulher = soma_idade_mulher / max(1, contador_mulher)  # Evita divisão por zero
media_idade_grupo = (soma_idade_homem + soma_idade_mulher) / max(1, contador_homem + contador_mulher)  # Evita divisão por zero

# Imprime os resultados
print(f"A idade média dos homens é: {media_idade_homem}")
print(f"A idade média das mulheres é: {media_idade_mulher}")
print(f"A idade média do grupo é: {media_idade_grupo}")