# -*- coding: utf-8 -*-
"""Temperatura.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nWTcoH4eoiVy2LO5AHLcDSVWorEfr6uy

Programa que solicita um número de pacientes e sua temperatura. Classificando em: Temperatura normal, febril,com febre e Febre alta
"""

p=int(input('Número de pacientes'))

soma=float()
for pacientes in range(0,p):
  temperatura=float(input('Digite a temperatura:'))
  if temperatura < 37.2:
    print('Temperatura normal')
  elif temperatura < 38.0:
    print('Febril')
  elif temperatura <39:
    print('Com febre')
  elif temperatura >=39:
    print('Febre alta')
  soma+=temperatura

print('\nmédia:',soma/(float(p)))