# -*- coding: utf-8 -*-
"""usuário e senha

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ex6D4xzJA9kY0kHiovDvSvchCY8pYh0s
"""

n=input("Digite o nome do usuário: ")
n=n.capitalize()
while s !=1234:
  s=float(input("Olá {}, digite a senha de usuário: ".format(n)))
  if s==1234:
   print('Bem vindo')
  else:
    print("Errado, tente novamente")