# -*- coding: utf-8 -*-
"""volume.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UIvCCOtoDyfCejaYuhx2aVYxb9m4tVCC

Retorno de volume de um cilindro
"""

from math import pi

r=float(input('input raio:'))

h=float(input('input altura:'))

vol=pi*r**2*h

print('volume = {:.4f}'.format(vol))