# -*- coding: utf-8 -*-
"""volume e consumo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17xYmnKIBu7WIN2P70IVDMxvn3AHDcTaa

dado a altura largura e comprimento em cm de um reservatório de água e o consumo diário dos utilizadores do reservatório em litros/dia
Este programa retorna:
1- Capacidade total do reservatório em litros
2- A autonomia do reservatório em dias
3- Classificação do consumo de acordo com a quantidade de dias de autonomia.
Elevado - < 2
moderado >2<=7
reduzido >7
"""

print('Insira os seguintes dados:')

h=float(input('Altura em cm:'))

l=float(input('Largura em cm:'))

c=float(input('Comprimento em cm:'))

consumo=float(input('Consumo médio diário em litros/dia: (insira somente números)'))

vol= l*h*c
print('seu volume é de:',vol,'cm cúbicos, ou',vol/1000,'litros cubicos')

consumo=consumo*1000

autonomia=vol/consumo
print(autonomia)

if autonomia < 2:
  print('Consumo alto')
elif autonomia <= 7:
  print('Consumo moderado')
elif autonomia > 7:
  print('Consumo reduzido')