# -*- coding: utf-8 -*-
"""while febre

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M2MCwbz_uhr1uK1pGKGX5jmiSt51wMj1
"""

media=float()
temp=float()
te=float()
while te<5:
  t=float(input("Digite a temperatura do paciente {}: ".format(te+1)))
  te=te+1
  temp=t
  if temp<37.3 and temp>35:
    print('O paciente {} está normal'.format(t))
  elif temp>37.2 and temp<39:
    print('O paciente {} está com febre'.format(t))
  elif temp>38.9:
    print('O paciente {} está com muita febre'.format(t))
  elif temp<35:
    print('O paciente está com hipotermia')
  elif temp>39.9:
    print('O paciente está com hipertermia')
  media=media+t
print("A média de temperatura dos pacintes é: ",media/5)