# -*- coding: utf-8 -*-
"""while pares

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19T2cQFNCCJ2alVvK93ZfqUp7RsftQkbb
"""

par=float()
while par<100:
 par=par+2
 print(par)