# -*- coding: utf-8 -*-
"""wpares.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oAQg8zawanUQtn3kzwC3e7lLp6yvMyiv
"""

Programa para dizer quais os valores pares de 0-100 sem uso de listas e for

x=100
while x!=0:
  if x%2 ==0:
    print(x,end=', ')
  x=x-1