# -*- coding: utf-8 -*-
"""wtemperatura.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RYMmajb5BRnDIQ_AcLYjcGweXB_-wOzh

Programa para classificar a temperatura digitada pelo usuário em normal, febril, com febre e alta utilizando while
"""

print('digite -1 caso deseje finalizar a operação')
temperatura=float(0)
somatemp=float(0)
numpac=float(0)
while temperatura!=-1:
  temperatura=float(input('temperatura do paciente:'))
  if temperatura < 37.2:
    print('Temperatura normal')
  elif temperatura < 38.0:
    print('Febril')
  elif temperatura <39:
    print('Com febre')
  elif temperatura >=39:
    print('Febre alta')

  somatemp=somatemp+temperatura
  numpac=numpac+1

print('média:',somatemp/(numpac-1))