# -*- coding: utf-8 -*-
"""ímpar ou par

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lc5na_Eg1X2LlbUF6tO7oR29XsfNmewE
"""

a=float(input("Escolha um número: "))

if a % 2 ==0:
  print("O número escolhido é par")
else:
 print("O número escolhido é ímpar")