# -*- coding: utf-8 -*-
"""Numeros pares de 1 a 100 usando for.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uEuFvKp4-tTTIHsy8L2GBc6JwyXOd_JG
"""

for numero in [0, 18, 56, 77, 95]:
    print(numero)
else:
    print("Acabou")

for numero in range (1000000):
  print(numero)
  if numero == 6000:
    break
  print("Até mais")

numeros = [1, 2, 3, 10, 12]
for numero in numeros:
  if numero == 15:
    break
  print(numero)
else:
    print("acabou")

numero=int(input("Digite seu numero: "))
for elemento in [7, 8, 17, 25, 38]:
  numero == elemento
  if numero == elemento:
    print(numero, "este numero esta correto!")
  break
if numero != elemento:
  print("Tem certeza que este celular é seu?!")

# Solicita ao usuário que insira um número
numero = int(input("Por favor, insira um número: "))

# Verifica se o número é par ou ímpar
if numero % 2 == 0:
    print(f"{numero} é par.")
else:
    print(f"{numero} é ímpar.")

